version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.23
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=admin
      - POSTGRES_SEEDS=postgres
      - POSTGRES_DB=temporal
    ports:
      - "7233:7233" # Temporal frontend
    depends_on:
      - postgres

  temporal-admin-tools:
    image: temporalio/admin-tools:latest
    stdin_open: true
    tty: true
    depends_on:
      - temporal

  temporal-web:
    image: temporalio/web:latest
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - "8088:8088"
    depends_on:
      - temporal

  postgres:
    image: postgres:15
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: