export enum BookingState {
	PENDING_APPROVAL = "IDLE",
	DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
	DRIVER_EN_ROUTE = "DRIVER_EN_ROUTE",
	DRIVER_ARRIVED = "DRIVER_ARRIVED",
	PICKUP_CONFIRMED = "PICKUP_CONFIRMED",
	DROPPED_OFF = "DROPPED_OFF",
	COMPLETED = "COMPLETED",
	CANCELLED_BY_RIDER = "CANCELLED_BY_RIDER",
	CANCELLED_BY_DRIVER = "CANCELLED_BY_DRIVER",
	NO_DRIVER_FOUND = "NO_DRIVER_FOUND",
	RIDE_EXPIRED = "RIDE_EXPIRED",
}

export enum BookingRequestState {
	DRIVER_ASSIGN_REQUEST = "DRIVER_ASSIGN_REQUEST",
	DRIVER_EN_ROUTE_REQUEST = "DRIVER_EN_ROUTE_REQUEST",
	DRIVER_ARRIVED_REQUEST = "DRIVER_ARRIVED_REQUEST",
	PICKUP_CONFIRM_REQUEST = "PICKUP_CONFIRM_REQUEST",
	DROPPED_OFF_REQUEST = "DROPPED_OFF_REQUEST",
	COMPLETE_RIDE_REQUEST = "COMPLETE_RIDE_REQUEST",
}

export const DRIVER_BOOKING_STATE_MAP = {
	[BookingRequestState.DRIVER_ASSIGN_REQUEST]: BookingState.DRIVER_ASSIGNED,
	[BookingRequestState.DRIVER_EN_ROUTE_REQUEST]: BookingState.DRIVER_EN_ROUTE,
	[BookingRequestState.DRIVER_ARRIVED_REQUEST]: BookingState.DRIVER_ARRIVED,
	[BookingRequestState.PICKUP_CONFIRM_REQUEST]: BookingState.PICKUP_CONFIRMED,
	[BookingRequestState.DROPPED_OFF_REQUEST]: BookingState.DROPPED_OFF,
	[BookingRequestState.COMPLETE_RIDE_REQUEST]: BookingState.COMPLETED,
};
